### ISSUE TITLE
Replace contenteditable with draft.js

### ISSUE THREAD

**Issue by dinostheo** [radient/editor-client#18]

**Comment by dinostheo** [comment]
Initially it should replace the basic functionality that our current editor (_contenteditable_) has `bold, link`.

**Comment by dinostheo** [comment]
Creating the link (aka substitute) functionality can be a task by itself.

**Comment by danillouz** [comment]
I created a branch `draftjs` to play around with draft and see the best way to implement it.

**Comment by danillouz** [comment]
Works nicely! 🔥💰💪💯
